package QuizApp;

public class QuestionAnswer
{
    public static String question[] =
    {        
        "What Was The Title Of The Last Film Paul Walker Completed Before He Died?",
        "Who Is Referred As 'Isai Puyal' In Tamil Music Industry?",
        "Name The Playback Singer Known For Her Rendition Of 'Munbe Vaa'?",
        "Which Gas Makes Up The Majority Of Earth's Atmosphere?",
        "Name The Largest Organ In Human Body?",
        "Which National Team Won 2022 World Cup Against France?",
        "Which Player Has More Collective Awards?",
        "Where Champions League Final 2023 Takes Place?",
        "The Coach One Who Currently Manages Paris Saint Germain?",
        "Which National Team Eden Hazard Played For?",
        "In Which Year Lionel Messi Joined Paris?",
        "Select The Indian Cricketer Who Scored 100 International Hundreds",
        "The Term LBW In Cricket Stands For",
        "In Options Which Is Not Considered As Object Oriented Programming Principle?",
        "What Is Class In Java?",
        "In Which Field Python Is Not Used?",
        "Gaming Console Known For Its Dual Shock Controllers Developed By Sony?",
        "Difference Between HashMap And HashTable?",
        "The Avenger With Great Strength And Incredible Green Rage?",
        "Which Data Structure Follows Last In First Out Principle?",
        "In Object Oriented Program, Process Used For Creating New Class Based On Existing Classs?",
        "Which Body Of Water Does Chennai's Coastline Border?",
        "Which Java Class Is The Ultimate Superclass For All Classes?",
        "Who Developed The Java Programming Language?",
        "The Technology Which Makes Iphone Screen More Responsive?",
        "Database Management System Known For Its Scalability And Flexibility In Handling Large Datasets?",
        "National Team That's Not Participating In World Cup 2023?",
        "Factorial For Value 6?",
        "Rectangle Has Length 8 Units And Width 5 Units Then Value Of Area?",
        "Which Of The Following Is Prime Number?",
        "Snapshot Used In Virtualization For The Purpose?",
        "What Gas Plants Absorb During Photosynthesis?",
        "Term Describes The Bending of Light As It Passes From One Medium To Another?",
        "The Term Used For The Smallest Unit For Digital Image?",
        "The Term Which Describes Gradual Transition From One Color To Another In Graphics?",
        "Who Is Famous For Thunder In Marvel Avengers?",
        "Who Portrayed Billionaire Genius Behind The Iron Man Suit?",
        "In Which Year First Iphone Released?",
        "In Which City Does The First 'Fast And Furious' Film Primarily Take Place?",
        "Condition Statements In Programming Are Used For?",
        "What Does CSS Stand For, In Web Development?",
        "Select The Version Control System From Below Given Options?",
        "In Which Year Griezmann Win World Cup With French National Team?",
        "The Essential Aspect For Personal Growth?",
        "The More You Take, The More You Leave Behind, What's That?",
        "What Has Keys And Can't Open Doors?",
        "I Have Keys But No Locks, I Have Space But No Room, You Can Enter But Can't Go Inside, What I'am?",
        "In Object Oriented Programming, Polymorphism Is Closely Related To Which Concept?",
        "Which Feature Of Android Allows Apps To Run In Background And Provides Updates Or Notifications?",
        "Which Car Is Famous For Its 'Hemi' Engine With Exceptional Power And Performance?",
        "In Which Category Cars You Would Find Features Like High Ground Clearance And All Wheel Drive For Mild Off Road Capabilities?"
    };

    public static String choices[][] =
    {
        {"Fast And Furious 6","Fast And Furious 7","Fast And Furious 8"},
        {"Harris jayaraj","Ilaiyaraja","Bala Subramanyam"},
        {"Shreya Ghoshal","Shweta Mohan","Chithra"},
        {"Oxygen","Carbon Dioxide","Nitrogen"},
        {"Skin","Lungs","Brain"},
        {"Argentina","Netherlands","Spain"},
        {"Lionel Messi","Zidane","Ronaldo"},
        {"London","Paris","Istanbul"},
        {"Zidane","Ronald","Luis Enrique"},
        {"Belgium","France","Netherlands"},
        {"2018","2021","2022"},
        {"Virat","Dhoni","Sachin"},
        {"Left Before Wicket","Leg Before Wicket","Last Ball Win"},
        {"Inheritance","Encapsulation","Multiple Inheritance"},
        {"Instance","Template","Virtual Machine"},
        {"Game Development","Data Analysis","Artificial Intelligence"},
        {"PlayStation","Xbox","Nintendo"},
        {"HashMap Is Synchronised","HashMap Allows Null Values","HashMap Is Not Preferable Over HashTable"},
        {"Hulk","Thor","Black Panther"},
        {"Linked List","Array","Stack"},
        {"Inheritance","Abstraction","Encapsulation"},
        {"Arabian Sea","Indian Ocean","Bay Of Bengal"},
        {"Object","Main","Root"},
        {"Torvalds","James Gosling","Larry Page"},
        {"Tap Sense","3D Touch","Haptic Touch"},
        {"MySql","Mongo Database","Sql Lite"},
        {"Netherlands","West Indies","Afghanistan"},
        {"720","20","120"},
        {"13","40","53"},
        {"7","35","77"},
        {"Taking ScreenShot","Sharing Virtual Machine","Cloning And Backup"},
        {"Carbon Dioxide","Oxygen","Carbon Monoxide"},
        {"Reflection","Refraction","Deflection"},{"Pixel","Resolution","Vector"},
        {"Gradient","Overlay","Opacity"},
        {"Iron Man","Loki","Thor"},
        {"Iron Man","Chris Hemsworth","Robert Downey Junior"},
        {"2006","2007","2008"},
        {"Miami","New York","Los Angeles"},
        {"Finding Errors","Decision Making","Function Declaration"},
        {"Cascading Style Sheet","Creative Style Sector","Compact Style Sheet"},
        {"Mercurial","Git","Both"},
        {"2014","2018","2022"},
        {"Discipline","Flexibility","Dominate Others"},
        {"Foot Steps","Dreams","Memories"},
        {"Piano","Car","Doors"},
        {"Wallet","Keyboard","Garage"},
        {"Inheritance","Abstraction","Encapsulation"},
        {"Push Notification","Launcher","Multi Tasking"},
        {"Dodge Charger","Dodge Challenger","Chevrolet Camaro"},
        {"Convertible","Sedan","Crossover"}
    };

    public static String correctAnswers[] =
    {
        "Fast And Furious 7","Ilaiyaraja","Shreya Ghoshal","Nitrogen","Skin",
        "Argentina","Lionel Messi","Istanbul","Luis Enrique","Belgium",
        "2021","Sachin","Leg Before Wicket","Multiple Inheritance","Template",
        "Game Development","PlayStation","HashMap Allows Null Values","Hulk","Stack",
        "Inheritance","Bay Of Bengal","Object","James Gosling","3D Touch",
        "Mongo Database","West Indies","720","40","7",
        "Cloning And Backup","Carbon Dioxide","Refraction","Pixel","Gradient",
        "Thor","Robert Downey Junior","2007","Los Angeles","Decision Making",
        "Cascading Style Sheet","Both","2018","Discipline","Memories",
        "Piano","Keyboard","Inheritance","Multi Tasking","Dodge Charger",
        "Crossover"
    };
}
